// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartHomeAPI.Models
{
    public partial class Mobile
    {
        public Mobile()
        {
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public string Uuid { get; set; }
        public string AppId { get; set; }
        public string DeviceName { get; set; }

        public virtual ICollection<User> Users { get; set; }
    }
}