// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartHomeAPI.Models
{
    public partial class Room
    {
        public Room()
        {
            Devices = new HashSet<Device>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public int UserId { get; set; }

        public virtual RoomType Type { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}