// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartHomeAPI.Models
{
    public partial class User
    {
        public User()
        {
            Rooms = new HashSet<Room>();
            Mobiles = new HashSet<Mobile>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int SettingId { get; set; }

        public virtual Setting Setting { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }

        public virtual ICollection<Mobile> Mobiles { get; set; }
    }
}